color_primary = '#00AFB0'
color_main_bg = '#007D7D'
color_white = '#FFFFFF'
color_soldier_card_title = '#000000'
color_soldier_card_text = '#565656'
color_gray_bg = '#F3F5F6'
color_text_field_border = '#C5C5C5'
color_login_activity_text = '#575757'

img_add = './res/img/add.png'
img_card_view_bg = './res/img/card_view_bg.png'
img_army_picture = './res/img/army_picture.png'
img_listview_shadow = './res/img/listview_shadow.png'
img_exit = './res/img/exit.png'
img_close = './res/img/close.png'
img_shadow_rect = './res/img/shadow_rect.png'
